/**
 * Generates migration 0002 (Better Auth's tables) for BOTH dialects with Better Auth's own schema generator
 * (getMigrations → compileMigrations, the same code its CLI uses), from the exact configuration the app runs
 * (src/server/auth/create-auth.ts), against a database that has every earlier migration applied:
 *
 *   npm run db:gen-auth-migrations            # prints both
 *   npm run db:gen-auth-migrations -- --write # writes db/migrations/sqlite/0002_auth.sql and
 *                                             # supabase/migrations/20261010000002_auth.sql
 *
 * The output is made idempotent (IF NOT EXISTS) and, for Postgres, gets row level security on every table,
 * no policies, and the Supabase default grants revoked (same rules as 0001). After a Better Auth upgrade,
 * add a NEW migration instead of regenerating 0002: auth.test.ts fails while Better Auth still wants changes.
 */
import fs from "node:fs";
import { Kysely, PGliteDialect } from "kysely";
import { getMigrations } from "better-auth/db/migration";
import { createAuth } from "../../src/server/auth/create-auth";
import type { Database } from "../../src/server/db/schema";
import { NodeSqliteDialect, openSqliteDatabase } from "../../src/server/db/dialects/sqlite-local";
import { readMigrations, repoPath, SQLITE_MIGRATIONS_DIR, POSTGRES_MIGRATIONS_DIR } from "../../src/server/db/migrations";
import { createPglite } from "../../src/server/db/testing/pglite";

const SECRET = "generator-only-secret-".padEnd(48, "g");
const BASE = { kind: "static" as const, url: "http://localhost:3000" };

/** Apply migrations BEFORE 0002 only (the generator diffs against what exists). */
function earlierSqlite(name: string): boolean {
  return name < "0002";
}
function earlierPostgres(name: string): boolean {
  return name < "20261010000002";
}

export async function rawSqlite(): Promise<string> {
  const sqlite = openSqliteDatabase(":memory:");
  for (const file of readMigrations(repoPath(SQLITE_MIGRATIONS_DIR), "sqlite").filter((f) => earlierSqlite(f.name))) sqlite.exec(file.sql);
  const db = new Kysely<Database>({ dialect: new NodeSqliteDialect({ database: sqlite }) });
  const auth = createAuth({ db, dialect: "sqlite", secret: SECRET, baseUrl: BASE });
  const { compileMigrations } = await getMigrations(auth.options);
  const sql = await compileMigrations();
  await db.destroy();
  return sql;
}

export async function rawPostgres(): Promise<string> {
  const pglite = await createPglite();
  for (const file of readMigrations(repoPath(POSTGRES_MIGRATIONS_DIR), "postgres").filter((f) => earlierPostgres(f.name))) {
    await pglite.exec(file.sql);
  }
  const db = new Kysely<Database>({ dialect: new PGliteDialect({ pglite }) });
  const auth = createAuth({ db, dialect: "postgres", secret: SECRET, baseUrl: BASE });
  const { compileMigrations } = await getMigrations(auth.options);
  const sql = await compileMigrations();
  await db.destroy();
  return sql;
}

const AUTH_TABLES = ["user", "session", "account", "verification", "twoFactor", "organization", "member", "invitation", "rateLimit"];

function statements(raw: string): string[] {
  return raw
    .split(/;\s*\n?/)
    .map((s) => s.trim())
    .filter(Boolean);
}

/** SQLite / D1: IF NOT EXISTS on every table and index. No semicolons in comments (wrangler splits on them). */
export function formatSqlite(raw: string): string {
  const body = statements(raw).map((stmt) =>
    stmt.replace(/^create table "/i, 'create table if not exists "').replace(/^create index "/i, 'create index if not exists "'),
  );
  return [
    "-- ClinForms 0002_auth (SQLite / Cloudflare D1): the Better Auth tables, GENERATED by",
    "-- scripts/db/gen-auth-migrations.ts from the app configuration (src/server/auth/create-auth.ts) with",
    "-- the Better Auth schema generator, then made idempotent. Kept in step with",
    "-- supabase/migrations/20261010000002_auth.sql (db/parity.test.ts checks tables and columns match).",
    "-- Better Auth conventions: camelCase columns, booleans INTEGER 0/1, dates ISO-8601 TEXT (type date).",
    "-- No quote marks or semicolons in these comments (wrangler splits the file itself).",
    "-- Do not edit by hand. After a Better Auth upgrade add a NEW migration (src/server/auth/auth.test.ts",
    "-- fails while Better Auth still wants schema changes).",
    "",
    ...body.map((stmt) => `${stmt};`),
    "",
  ].join("\n");
}

function qualify(stmt: string): string {
  return stmt
    .replace(/^create table "([^"]+)"/i, 'create table if not exists public."$1"')
    .replace(/^create index "([^"]+)" on "([^"]+)"/i, 'create index if not exists "$1" on public."$2"')
    .replace(/references "([^"]+)"/g, 'references public."$1"');
}

/** Postgres / Supabase: idempotent, public-qualified, RLS on every table with no policies, default grants revoked. */
export function formatPostgres(raw: string): string {
  const tables = AUTH_TABLES.map((t) => `public."${t}"`);
  return [
    "-- ClinForms 0002_auth (Postgres / Supabase): Better Auth's tables, GENERATED by",
    "-- scripts/db/gen-auth-migrations.ts from the app's own configuration (src/server/auth/create-auth.ts) with",
    "-- Better Auth's schema generator, then made idempotent. Kept in step with db/migrations/sqlite/0002_auth.sql",
    "-- (db/parity.test.ts checks tables and columns match). Better Auth's conventions here: camelCase columns,",
    "-- boolean, timestamptz.",
    "-- Every table has row level security ENABLED and NO policies: the Data API (anon / authenticated) cannot",
    "-- read or write them. The app connects as the table owner through the pooler.",
    "-- Do not edit by hand. After a Better Auth upgrade add a NEW migration.",
    "",
    ...statements(raw).map((stmt) => `${qualify(stmt)};`),
    "",
    "-- Row level security on every table, with no policies.",
    ...tables.map((t) => `alter table ${t} enable row level security;`),
    "",
    "-- Supabase roles: take away the default table grants too (defence in depth on top of RLS). The roles do not",
    "-- exist on a plain Postgres (or PGlite in tests), hence the checks.",
    "do $$",
    "declare",
    "  r text;",
    "begin",
    "  foreach r in array array['anon', 'authenticated'] loop",
    "    if exists (select 1 from pg_roles where rolname = r) then",
    "      execute format(",
    `        'revoke all on table ${tables.join(", ")} from %I',`,
    "        r",
    "      );",
    "    end if;",
    "  end loop;",
    "end;",
    "$$;",
    "",
  ].join("\n");
}

export const SQLITE_FILE = "db/migrations/sqlite/0002_auth.sql";
export const POSTGRES_FILE = "supabase/migrations/20261010000002_auth.sql";

async function main() {
  const sqlite = formatSqlite(await rawSqlite());
  const postgres = formatPostgres(await rawPostgres());
  if (process.argv.includes("--write")) {
    fs.writeFileSync(repoPath(SQLITE_FILE), sqlite);
    fs.writeFileSync(repoPath(POSTGRES_FILE), postgres);
    console.log(`Wrote ${SQLITE_FILE} and ${POSTGRES_FILE}.`);
  } else {
    console.log(`-- ${SQLITE_FILE}\n${sqlite}\n-- ${POSTGRES_FILE}\n${postgres}`);
  }
}

if (process.argv[1] && /gen-auth-migrations\.ts$/.test(process.argv[1])) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
