import "server-only";

/**
 * Registry of demo drafts, statically imported so the serverless bundle always contains them.
 * Keys: `${externalPatientId}__${templateId}` (built-in templates) and
 * `${externalPatientId}__form-${sampleId}` (referrer forms). Regenerated by
 * scripts/medreport/record-demo-drafts.ts from the .json files in this folder.
 *
 * Owner: ai agent.
 */
import simPat001FormAshcroftUpdateReport from "./sim-pat-001__form-ashcroft-update-report.json";
import simPat001FormHarrowPikeTreatingPhysio from "./sim-pat-001__form-harrow-pike-treating-physio.json";
import simPat001FormMeridianDischargeReport from "./sim-pat-001__form-meridian-discharge-report.json";
import simPat001FormNorthfieldRehabProgress from "./sim-pat-001__form-northfield-rehab-progress.json";
import simPat001SolicitorRtaTreatingPhysio from "./sim-pat-001__solicitor-rta-treating-physio.json";
import simPat002EmployerFitnessForWork from "./sim-pat-002__employer-fitness-for-work.json";
import simPat002FormKingswayRtwAssessment from "./sim-pat-002__form-kingsway-rtw-assessment.json";
import simPat002FormNorthfieldRehabProgress from "./sim-pat-002__form-northfield-rehab-progress.json";

export const DEMO_DRAFT_SOURCES: Record<string, unknown> = {
  "sim-pat-001__form-ashcroft-update-report": simPat001FormAshcroftUpdateReport,
  "sim-pat-001__form-harrow-pike-treating-physio": simPat001FormHarrowPikeTreatingPhysio,
  "sim-pat-001__form-meridian-discharge-report": simPat001FormMeridianDischargeReport,
  "sim-pat-001__form-northfield-rehab-progress": simPat001FormNorthfieldRehabProgress,
  "sim-pat-001__solicitor-rta-treating-physio": simPat001SolicitorRtaTreatingPhysio,
  "sim-pat-002__employer-fitness-for-work": simPat002EmployerFitnessForWork,
  "sim-pat-002__form-kingsway-rtw-assessment": simPat002FormKingswayRtwAssessment,
  "sim-pat-002__form-northfield-rehab-progress": simPat002FormNorthfieldRehabProgress,
};
