const L = require("./lib.cjs");
const F = require("./flows.cjs");
const P = process.env.PFX || "d";
(async () => {
  const { ctx, page, problems, net } = await L.open({});
  await L.step("E1 sandbox Documents tab lists filed forms", async () => {
    for (const pid of ["sim-pat-001", "sim-pat-002"]) {
      await page.goto(`${L.BASE}/pms-sandbox/patients/${pid}`);
      await page.waitForLoadState("networkidle");
      await page.getByRole("tab", { name: /Documents/ }).click();
      await page.waitForTimeout(800);
      const txt = await page.locator("[role=tabpanel]:visible").first().innerText();
      console.log(`   ${pid}:`, txt.replace(/\n+/g, " | ").slice(0, 500));
      await L.shot(page, `${P}-50-sandbox-docs-${pid}`, false);
      L.assert(/SIGNED|\.docx|\.pdf/i.test(txt), "files listed");
      if (pid === "sim-pat-001") L.assert(/\.docx/.test(txt) && /\.pdf/.test(txt), "Word and PDF copies filed");
    }
  });
  await L.step("E2 notes upload: printed notes PDF -> what the drafting service receives -> form", async () => {
    await page.goto(`${L.BASE}/reports/new`);
    await page.waitForLoadState("networkidle");
    await page.getByRole("button", { name: /Upload the notes/ }).click();
    await page.waitForTimeout(400);
    await L.shot(page, `${P}-51-upload-notes`, false);
    await page.getByRole("button", { name: /Try the printed notes PDF/ }).click();
    await page.getByText(/Priya Nair/).first().waitFor({ timeout: 30000 });
    await page.waitForTimeout(800);
    await L.shot(page, `${P}-52-upload-preview`);
    const txt = await page.locator("main").innerText();
    console.log("   preview:", txt.replace(/\n+/g, " | ").slice(0, 600));
    await page.getByRole("button", { name: /See exactly what the drafting service receives/ }).click();
    const pre = page.locator("#ai-payload-body pre");
    await pre.waitFor({ timeout: 20000 });
    const payload = await pre.innerText();
    console.log("   payload head:", payload.replace(/\n+/g, " | ").slice(0, 400));
    L.assert(/\[CLAIMANT\]/.test(payload), "name replaced with [CLAIMANT]");
    L.assert(!/Priya|Nair/.test(payload), "patient name absent from what the drafting service receives");
    await page.locator("#ai-payload-body").scrollIntoViewIfNeeded();
    await L.shot(page, `${P}-52a-ai-payload`, false);
    await page.getByRole("button", { name: "Choose the referrer form" }).click();
    await page.waitForTimeout(500);
    await page.getByRole("radio", { name: /Harrow & Pike/ }).click();
    await page.getByRole("button", { name: "Complete this form" }).click();
    await page.waitForTimeout(2500);
    await L.shot(page, `${P}-52b-upload-completing`, false);
    const open = page.getByRole("link", { name: /review|Open/i }).or(page.getByRole("button", { name: /review|Open/i }));
    if (!/\/reports\/rpt_/.test(page.url())) await open.first().click();
    await page.waitForURL(/\/reports\/(?!new)[^/?]+$/, { timeout: 60000 });
    await page.locator("[id^='q-F-']").first().waitFor({ timeout: 20000 });
    await page.waitForTimeout(1500);
    await L.shot(page, `${P}-53-upload-review`, false);
    console.log("   header:", (await page.locator("header").nth(1).innerText()).replace(/\n+/g, " | ").slice(0, 300));
  });
  await L.step("E3 batch with two pairs", async () => {
    await page.goto(`${L.BASE}/reports/batch`);
    await page.waitForLoadState("networkidle");
    await page.waitForTimeout(1500);
    const forms = await page.evaluate(() => JSON.parse(localStorage.getItem("medreport.forms") || "[]").map((f) => ({ id: f.id, sampleId: f.sampleId })));
    const hp = forms.find((f) => f.sampleId === "harrow-pike-treating-physio").id;
    const kw = forms.find((f) => f.sampleId === "kingsway-rtw-assessment").id;
    await page.getByLabel("Referrer form for Megan Hart").selectOption(hp);
    await page.getByRole("button", { name: "Add Megan Hart to the queue" }).click();
    await page.getByLabel("Referrer form for Daniel Brooks").selectOption(kw);
    await page.getByRole("button", { name: "Add Daniel Brooks to the queue" }).click();
    await L.shot(page, `${P}-54-batch-queued`, false);
    const t = Date.now();
    await page.getByRole("button", { name: /^Run/ }).click();
    await page.waitForFunction(() => (document.body.innerText.match(/Ready for review|Needs input/g) || []).length >= 2, null, { timeout: 120000 });
    console.log("   batch done in", Date.now() - t, "ms");
    await page.waitForTimeout(800);
    const q = await page.locator("section[aria-labelledby='queue-heading']").innerText();
    console.log("   queue:", q.replace(/\n+/g, " | ").slice(0, 600));
    await L.shot(page, `${P}-55-batch-done`);
  });
  await L.step("E4 home lists the completed forms", async () => {
    await page.goto(`${L.BASE}/reports`);
    await page.waitForLoadState("networkidle");
    await page.waitForTimeout(1200);
    await L.shot(page, `${P}-56-home-with-reports`);
    const txt = await page.locator("main").innerText();
    console.log("   approved count:", (txt.match(/Approved/g) || []).length);
  });
  await L.step("E5 built-in templates fallback page", async () => {
    await page.goto(`${L.BASE}/reports/templates`);
    await page.waitForLoadState("networkidle");
    await page.waitForTimeout(1000);
    await L.shot(page, `${P}-57-templates`);
  });
  await L.step("E6 security page + Demo tools menu", async () => {
    await page.goto(`${L.BASE}/reports`);
    await page.waitForLoadState("networkidle");
    await page.waitForTimeout(800);
    await page.locator("summary", { hasText: "Demo tools" }).click();
    await page.waitForTimeout(300);
    L.assert(await page.getByRole("button", { name: "Reset demo" }).isVisible(), "reset inside Demo tools");
    await L.shot(page, `${P}-58-demo-tools`, false);
    await page.goto(`${L.BASE}/reports/security`);
    await page.waitForLoadState("networkidle");
    await page.waitForTimeout(800);
    const t = await page.locator("main").innerText();
    L.assert(/Data Processing Agreement/.test(t) && /\[CLAIMANT\]/.test(t), "security page content");
    await L.shot(page, `${P}-59-security`);
  });
  let meg;
  await L.step("E7 Megan -> Ashcroft FLAT PDF -> approve -> final PDF -> file", async () => {
    meg = await F.launch(ctx, page, "sim-pat-001");
    const r = await F.chooseAndGenerate(meg, /Ashcroft/);
    console.log("   generate:", JSON.stringify(r));
    console.log("   flags before:", (await F.flagsText(meg)).slice(0, 700));
    const f03 = await meg.locator("#q-F-03").innerText();
    console.log("   F-03:", f03.replace(/\n+/g, " | ").slice(0, 300));
    await F.addOwn(meg, "F-09", "In my opinion the residual intermittent neck ache should settle within three to six months with her home exercise programme.");
    const c2 = meg.locator("#q-F-10");
    if (await c2.getByLabel("No", { exact: true }).count()) await c2.getByLabel("No", { exact: true }).check();
    await F.resolveAll(meg, Array.from({ length: 16 }, (_, i) => `F-${String(i + 1).padStart(2, "0")}`));
    console.log("   own voice:", await F.ownVoice(meg, `${P}-60a-ashcroft-own-voice`));
    await meg.waitForTimeout(800);
    const f = await F.flagsText(meg);
    console.log("   flags after:", f.slice(0, 700));
    L.assert(/Nothing blocks approval/.test(f), "nothing blocks");
    await meg.getByRole("tab", { name: "Preview" }).click();
    await meg.locator("[role=tabpanel][data-state=active] canvas").first().waitFor({ timeout: 30000 });
    await meg.waitForTimeout(2500);
    await L.shot(meg, `${P}-60-ashcroft-preview`, false);
    await F.approve(meg, null);
    console.log("   pdf:", await F.download(meg, "Completed form (PDF)", "megan-hart_ashcroft_FINAL.pdf"));
    await meg.getByRole("button", { name: /Save to clinic record/ }).click();
    await meg.getByText(/Filed to the Simulated TM3 record/).first().waitFor({ timeout: 30000 });
    await L.shot(meg, `${P}-61-ashcroft-approved`, false);
  });
  await L.step("E8 amendment of an approved form", async () => {
    const before = meg.url();
    await meg.getByRole("button", { name: /Create amended version/ }).click();
    await meg.waitForURL((u) => u.toString() !== before && /\/reports\/[^/?]+$/.test(u.toString()), { timeout: 20000 });
    await meg.getByText(/Amended – v2/).first().waitFor({ timeout: 20000 });
    await meg.waitForTimeout(800);
    const rep = await F.reportJson(meg);
    console.log("   amended:", JSON.stringify({ version: rep.version, amends: rep.amends, status: rep.status }));
    L.assert(rep.version === 2 && rep.amends && rep.status === "draft", "v2 draft amends v1");
    await L.shot(meg, `${P}-62-amended-v2`, false);
  });
  console.log("PROBLEMS:\n" + problems.join("\n"));
  console.log("NET>=400:\n" + net.join("\n"));
  await ctx.close();
})().catch((e) => { console.error(e); process.exit(1); });
