import "server-only";

/**
 * Bundled fictional referrer forms for the demo (GET /forms/samples, GET /forms/samples/{id}/file).
 *
 * Each sample is a referrer's OWN form with its own layout, headings and questions – an MLC's Word form
 * with answer cells in tables, an insurer's fillable PDF, a case manager's heading-based Word form with
 * "Answer: ____" lines and tick boxes, and a claims handler's boxed Word form with content controls (left
 * un-mapped for the live "upload a new form" demo). The files are generated by
 * scripts/medreport/build-demo-forms.mjs into forms/samples/generated/<id>.<ext>.b64.ts (base64 modules,
 * server-only) and loaded lazily. Pre-confirmed form maps (forms/samples/maps/*.ts, bound to the file's
 * SHA-256 via generated/manifest.ts) are attached as `form` with `builtIn: true` and `sampleId`.
 *
 * Every organisation name ends with "(fictional)".
 *
 * Owner: forms-engine agent (entries and files); the ai agent may supply recorded `form` maps.
 */
import type { FormSample } from "../../api/contract";
import type { FormDefinition, FormKind, FormMimeType, ReferrerInfo } from "../../core/types";
import { sha256Hex } from "../file";
import { SAMPLE_FORM_FILES, type SampleFormFileId } from "./generated/manifest";

export interface SampleFormEntry {
  /** Stable ID, e.g. "harrow-pike-treating-physio". */
  id: string;
  title: string;
  description: string;
  referrer: ReferrerInfo;
  fileName: string;
  mimeType: FormMimeType;
  kind: FormKind;
  highlights: string[];
  /** The original file bytes (lazy import of the generated base64 module). */
  loadFile(): Promise<Uint8Array>;
  /** Pre-confirmed form map for this exact file, when one has been recorded (seeded into the library). */
  loadForm?(): Promise<FormDefinition | undefined>;
  /**
   * A pre-written map that is NOT seeded into the library: POST /forms/analyse returns it (as a
   * proposal for staff to confirm) when this exact file is uploaded and no recorded analysis exists.
   */
  loadPrewrittenAnalysis?(): Promise<FormDefinition | undefined>;
}

function bytesOf(base64: string): Uint8Array {
  return new Uint8Array(Buffer.from(base64, "base64"));
}

function fileFacts(id: SampleFormFileId, kind?: FormKind): Pick<SampleFormEntry, "fileName" | "mimeType" | "kind"> {
  const f = SAMPLE_FORM_FILES[id];
  return { fileName: f.fileName, mimeType: f.mimeType, kind: kind ?? (f.mimeType === "application/pdf" ? "pdf_acroform" : "docx") };
}

/** The bundled samples, in display order. */
export const SAMPLE_FORMS: readonly SampleFormEntry[] = [
  {
    id: "harrow-pike-treating-physio",
    title: "Treating Physiotherapist Report",
    description:
      "A medico-legal company's Word form for a personal injury claim: claimant details and clinical questions in tables, with the answers written into the empty answer cells.",
    referrer: { name: "Harrow & Pike Medico-Legal (fictional)", type: "mlc" },
    ...fileFacts("harrow-pike-treating-physio"),
    highlights: [
      "Word form with answer cells in tables (Part A details, Part B question | answer)",
      "Two blanks in one answer box: sessions attended and failed to attend",
      "Maximum medical improvement asked as ☐ Yes ☐ No",
      "Prognosis, functional restrictions and treatment recommendations asked separately",
    ],
    loadFile: async () => bytesOf((await import("./generated/harrow-pike-treating-physio.docx.b64")).HARROW_PIKE_TREATING_PHYSIO_DOCX_BASE64),
    loadForm: async () => (await import("./maps/harrow-pike")).HARROW_PIKE_FORM,
  },
  {
    id: "northfield-rehab-progress",
    title: "Rehabilitation Progress Report",
    description:
      "An insurer's fillable PDF: the fields are filled in place and the final copy is flattened. Different order and wording – diagnosis first, fitness for work as a radio button, prognosis last.",
    referrer: { name: "Northfield Assurance (fictional)", type: "insurer" },
    ...fileFacts("northfield-rehab-progress"),
    highlights: [
      "Fillable PDF (AcroForm): text, multi-line, number and tick-box fields",
      "“Is the claimant fit for work?” as Yes / No / Modified duties radio buttons",
      "Functional limitations and prognosis worded differently from the MLC form",
      "Long answers shrink to fit, or continue on a continuation sheet",
    ],
    loadFile: async () => bytesOf((await import("./generated/northfield-rehab-progress.pdf.b64")).NORTHFIELD_REHAB_PROGRESS_PDF_BASE64),
    loadForm: async () => (await import("./maps/northfield")).NORTHFIELD_FORM,
  },
  {
    id: "kingsway-rtw-assessment",
    title: "Return to Work Assessment",
    description:
      "A case manager's heading-based Word form: numbered questions with “Answer: ____” lines and dotted continuation lines, several blanks on one line and tick-box lines for fitness for work.",
    referrer: { name: "Kingsway Case Management (fictional)", type: "case_manager" },
    ...fileFacts("kingsway-rtw-assessment"),
    highlights: [
      "Numbered headings, each followed by “Answer: ____” and dotted lines",
      "Several blanks on one line (employee name and date of birth)",
      "Fitness for normal and for modified duties as ☐ tick-box lines",
      "Return-to-work context: past medical and social history are kept out",
    ],
    loadFile: async () => bytesOf((await import("./generated/kingsway-rtw-assessment.docx.b64")).KINGSWAY_RTW_ASSESSMENT_DOCX_BASE64),
    loadForm: async () => (await import("./maps/kingsway")).KINGSWAY_FORM,
  },
  {
    id: "ashcroft-update-report",
    title: "Physiotherapy Update Report",
    description:
      "A medico-legal agency's FLAT PDF – printed questions and ruled lines, no fillable fields. Upload it to see a non-fillable form completed: the answers are written onto the page at its answer lines.",
    referrer: { name: "Ashcroft Medical Reporting (fictional)", type: "mlc" },
    ...fileFacts("ashcroft-update-report", "pdf_flat"),
    highlights: [
      "Flat PDF: no form fields at all – the answers are written onto the page",
      "Ruled answer lines under each question, a Yes / No line and a declaration",
      "Prognosis and further treatment asked as the clinician's own opinion",
      "Not in the library yet – upload it to map and confirm it",
    ],
    loadFile: async () => bytesOf((await import("./generated/ashcroft-update-report.pdf.b64")).ASHCROFT_UPDATE_REPORT_PDF_BASE64),
    loadPrewrittenAnalysis: async () => (await import("./maps/ashcroft")).ASHCROFT_FORM,
  },
  {
    id: "meridian-discharge-report",
    title: "Physiotherapy Discharge Report",
    description:
      "A claims handler's Word form in bordered boxes, with Word content controls (“Click or tap here to enter text.”) and tick-box controls. Not mapped yet: upload it to see a new form analysed.",
    referrer: { name: "Meridian Claims Services (fictional)", type: "insurer" },
    ...fileFacts("meridian-discharge-report"),
    highlights: [
      "Bordered section boxes with the answer space under each question",
      "Word content controls and tick-box content controls",
      "Questions phrased differently (“ability to carry out normal daily activities”)",
      "No saved mapping – the live “analyse a new form” demo",
    ],
    loadFile: async () => bytesOf((await import("./generated/meridian-discharge-report.docx.b64")).MERIDIAN_DISCHARGE_REPORT_DOCX_BASE64),
  },
];

export function getSampleForm(id: string): SampleFormEntry | undefined {
  return SAMPLE_FORMS.find((s) => s.id === id);
}

/** The sample whose file has this SHA-256 (e.g. a sample re-uploaded through POST /forms/analyse). */
export async function findSampleBySha256(sha256: string): Promise<SampleFormEntry | undefined> {
  for (const entry of SAMPLE_FORMS) {
    if (SAMPLE_FORM_FILES[entry.id as SampleFormFileId]?.sha256 === sha256) return entry;
  }
  return undefined;
}

/** Sample metadata for GET /forms/samples (hashes computed from the bytes, so they always match). */
export async function listSampleForms(): Promise<FormSample[]> {
  const samples: FormSample[] = [];
  for (const entry of SAMPLE_FORMS) {
    const bytes = await entry.loadFile();
    const sha256 = sha256Hex(bytes);
    const form = await entry.loadForm?.();
    samples.push({
      id: entry.id,
      title: entry.title,
      description: entry.description,
      referrer: entry.referrer,
      kind: entry.kind,
      file: { fileName: entry.fileName, mimeType: entry.mimeType, sha256, sizeBytes: bytes.byteLength },
      highlights: entry.highlights,
      // A recorded map is only offered for the exact file it was made from.
      ...(form && form.file.sha256 === sha256 && { form: { ...form, builtIn: true, sampleId: entry.id } }),
    });
  }
  return samples;
}
