import "server-only";

/**
 * Registry of recorded form analyses (real Claude output for the bundled sample forms), statically
 * imported so the serverless bundle always contains them. Keys: sample ID. Regenerated by
 * scripts/medreport/record-form-analyses.ts from the .json files in this folder.
 *
 * Owner: ai agent.
 */
import harrowPikeTreatingPhysio from "./harrow-pike-treating-physio.json";
import kingswayRtwAssessment from "./kingsway-rtw-assessment.json";
import meridianDischargeReport from "./meridian-discharge-report.json";
import northfieldRehabProgress from "./northfield-rehab-progress.json";

export const RECORDED_FORM_ANALYSIS_SOURCES: Record<string, unknown> = {
  "harrow-pike-treating-physio": harrowPikeTreatingPhysio,
  "kingsway-rtw-assessment": kingswayRtwAssessment,
  "meridian-discharge-report": meridianDischargeReport,
  "northfield-rehab-progress": northfieldRehabProgress,
};
