/**
 * Builds the fictional "printed clinical notes" PDF of the Priya Nair sample case (the same content as
 * the pasted-notes sample), laid out like a notes report printed from a clinic system: a title, the
 * patient and referral lines, then one block per note with a dated heading and labelled S/O/A/P lines,
 * page numbers in the footer. Written as base64 to
 * src/modules/medreport/connectors/file-import/samples/generated/priya-nair-notes.pdf.b64.ts.
 *
 *   node --import ./scripts/medreport/test-setup.mjs --import tsx scripts/medreport/build-notes-pdf.ts
 *
 * Deterministic (fixed dates, no metadata timestamps). Fictional data only.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import { buildSampleText } from "@/modules/medreport/connectors/file-import/samples";

const OUT = path.join(process.cwd(), "src/modules/medreport/connectors/file-import/samples/generated/priya-nair-notes.pdf.b64.ts");
const W = 595.28;
const H = 841.89;
const M = 50;
const SIZE = 9.5;
const LH = 13;

const winAnsi = (s: string) => s.replace(/→/g, "->").replace(/[“”]/g, '"').replace(/[‘’]/g, "'");

function wrap(text: string, font: PDFFont, size: number, width: number): string[] {
  const out: string[] = [];
  let line = "";
  for (const word of text.split(/\s+/)) {
    const next = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(next, size) > width && line) {
      out.push(line);
      line = word;
    } else line = next;
  }
  if (line) out.push(line);
  return out;
}

async function main() {
  const doc = await PDFDocument.create();
  doc.setTitle("Clinical notes report – fictional sample");
  doc.setProducer("ClinForms sample generator");
  doc.setCreator("ClinForms");
  const fixed = new Date("2026-10-06T09:00:00Z");
  doc.setCreationDate(fixed);
  doc.setModificationDate(fixed);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const pages: PDFPage[] = [];
  let page!: PDFPage;
  let y = 0;
  const newPage = () => {
    page = doc.addPage([W, H]);
    pages.push(page);
    page.drawText("Riverside Physiotherapy (fictional) – clinical notes report – fictional sample data", { x: M, y: H - 30, size: 7.5, font, color: rgb(0.45, 0.48, 0.55) });
    y = H - 60;
  };
  newPage();
  page.drawText("Clinical notes report", { x: M, y, size: 16, font: bold, color: rgb(0.06, 0.09, 0.2) });
  y -= 18;
  page.drawText("Printed 06/10/2026 from the clinic system", { x: M, y, size: 9, font, color: rgb(0.35, 0.38, 0.45) });
  y -= 26;

  const lines = winAnsi(buildSampleText()).split("\n");
  for (const raw of lines) {
    if (!raw.trim()) {
      y -= LH * 0.6;
      continue;
    }
    const heading = /^\d{2}\/\d{2}\/\d{4}/.test(raw);
    const f = heading ? bold : font;
    const size = heading ? 10.5 : SIZE;
    const wrapped = wrap(raw, f, size, W - 2 * M - (heading ? 0 : 12));
    if (heading && y - LH * 4 < M + 20) newPage();
    if (heading) y -= 4;
    wrapped.forEach((l, i) => {
      if (y < M + 20) newPage();
      page.drawText(l, { x: M + (heading || i === 0 ? 0 : 12), y, size, font: f, color: rgb(0.06, 0.09, 0.2) });
      y -= LH;
    });
  }
  pages.forEach((p, i) => {
    const label = `Page ${i + 1} of ${pages.length}`;
    p.drawText(label, { x: W - M - font.widthOfTextAtSize(label, 8), y: 28, size: 8, font, color: rgb(0.45, 0.48, 0.55) });
  });

  const bytes = await doc.save({ useObjectStreams: false });
  const b64 = Buffer.from(bytes).toString("base64");
  writeFileSync(
    OUT,
    `/**\n * GENERATED by scripts/medreport/build-notes-pdf.ts – do not edit. Fictional "printed clinical notes" PDF\n * of the Priya Nair sample case (base64). Browser-safe string.\n */\nexport const PRIYA_NAIR_NOTES_PDF_BASE64 =\n  ${JSON.stringify(b64)};\n`,
  );
  console.log(`Wrote ${path.relative(process.cwd(), OUT)} (${bytes.byteLength} bytes, ${pages.length} pages)`);
}

void main();
