import "server-only";

/**
 * Registers the PDF font: DejaVu Sans regular + bold (Bitstream Vera licence, see fonts/LICENSE-DejaVu.txt),
 * bundled as base64 modules (generated by scripts/medreport/build-templates.mjs), written ONCE to
 * os.tmpdir() and registered with Font.register by path. No runtime URL fetch. The built-in Helvetica
 * cannot draw → ✓ ≥ and friends, DejaVu Sans can.
 *
 * DejaVu Sans has no italic in this bundle, so italic styles map to the upright faces (the house layout
 * does not use italics).
 *
 * Owner: forms-engine agent (formerly docgen).
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import type { Font as ReactPdfFont } from "@react-pdf/renderer";
import { DEJAVU_SANS_BOLD_TTF_BASE64 } from "./fonts/dejavu-sans-bold.b64";
import { DEJAVU_SANS_TTF_BASE64 } from "./fonts/dejavu-sans.b64";

/** Font family name to use in react-pdf styles. */
export const PDF_FONT_FAMILY = "DejaVu Sans";

let registered = false;

/** Write a font file unless an identical one is already there (atomic rename, safe across instances). */
function materialise(dir: string, name: string, base64: string): string {
  const target = path.join(dir, name);
  const bytes = Buffer.from(base64, "base64");
  try {
    if (fs.statSync(target).size === bytes.length) return target;
  } catch {
    // not written yet
  }
  const tmp = `${target}.${process.pid}.${Date.now()}.tmp`;
  fs.writeFileSync(tmp, bytes);
  fs.renameSync(tmp, target);
  return target;
}

/**
 * Idempotent: registers the family the first time it is called in this process. `Font` comes from the
 * dynamically imported @react-pdf/renderer (ESM-only; a static import breaks CommonJS callers such as
 * the node:test runner).
 */
export function ensurePdfFonts(Font: typeof ReactPdfFont): void {
  if (registered) return;
  const dir = path.join(os.tmpdir(), "appstackx-reports-fonts-v1");
  fs.mkdirSync(dir, { recursive: true });
  const regular = materialise(dir, "DejaVuSans.ttf", DEJAVU_SANS_TTF_BASE64);
  const bold = materialise(dir, "DejaVuSans-Bold.ttf", DEJAVU_SANS_BOLD_TTF_BASE64);
  Font.register({
    family: PDF_FONT_FAMILY,
    fonts: [
      { src: regular, fontWeight: 400 },
      { src: bold, fontWeight: 700 },
      { src: regular, fontWeight: 400, fontStyle: "italic" },
      { src: bold, fontWeight: 700, fontStyle: "italic" },
    ],
  });
  // Never hyphenate (medico-legal text should not break words with inserted hyphens).
  Font.registerHyphenationCallback((word) => [word]);
  registered = true;
}
