-- ClinForms 0002_auth (SQLite / Cloudflare D1): the Better Auth tables, GENERATED by
-- scripts/db/gen-auth-migrations.ts from the app configuration (src/server/auth/create-auth.ts) with
-- the Better Auth schema generator, then made idempotent. Kept in step with
-- supabase/migrations/20261010000002_auth.sql (db/parity.test.ts checks tables and columns match).
-- Better Auth conventions: camelCase columns, booleans INTEGER 0/1, dates ISO-8601 TEXT (type date).
-- No quote marks or semicolons in these comments (wrangler splits the file itself).
-- Do not edit by hand. After a Better Auth upgrade add a NEW migration (src/server/auth/auth.test.ts
-- fails while Better Auth still wants schema changes).

create table if not exists "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" integer not null, "image" text, "createdAt" date not null, "updatedAt" date not null, "twoFactorEnabled" integer);
create table if not exists "session" ("id" text not null primary key, "expiresAt" date not null, "token" text not null unique, "createdAt" date not null, "updatedAt" date not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade, "activeOrganizationId" text);
create table if not exists "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" date, "refreshTokenExpiresAt" date, "scope" text, "password" text, "createdAt" date not null, "updatedAt" date not null);
create table if not exists "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" date not null, "createdAt" date not null, "updatedAt" date not null);
create table if not exists "twoFactor" ("id" text not null primary key, "secret" text not null, "backupCodes" text not null, "userId" text not null references "user" ("id") on delete cascade, "verified" integer, "failedVerificationCount" integer, "lockedUntil" date);
create table if not exists "organization" ("id" text not null primary key, "name" text not null, "slug" text not null unique, "logo" text, "createdAt" date not null, "metadata" text);
create table if not exists "member" ("id" text not null primary key, "organizationId" text not null references "organization" ("id") on delete cascade, "userId" text not null references "user" ("id") on delete cascade, "role" text not null, "createdAt" date not null);
create table if not exists "invitation" ("id" text not null primary key, "organizationId" text not null references "organization" ("id") on delete cascade, "email" text not null, "role" text, "status" text not null, "expiresAt" date not null, "createdAt" date not null, "inviterId" text not null references "user" ("id") on delete cascade);
create table if not exists "rateLimit" ("id" text not null primary key, "key" text not null unique, "count" integer not null, "lastRequest" bigint not null);
create index if not exists "session_userId_idx" on "session" ("userId");
create index if not exists "account_userId_idx" on "account" ("userId");
create index if not exists "verification_identifier_idx" on "verification" ("identifier");
create index if not exists "twoFactor_secret_idx" on "twoFactor" ("secret");
create index if not exists "twoFactor_userId_idx" on "twoFactor" ("userId");
create index if not exists "member_organizationId_idx" on "member" ("organizationId");
create index if not exists "member_userId_idx" on "member" ("userId");
create index if not exists "invitation_organizationId_idx" on "invitation" ("organizationId");
create index if not exists "invitation_email_idx" on "invitation" ("email");
