-- ClinForms 0002_auth (Postgres / Supabase): Better Auth's tables, GENERATED by
-- scripts/db/gen-auth-migrations.ts from the app's own configuration (src/server/auth/create-auth.ts) with
-- Better Auth's schema generator, then made idempotent. Kept in step with db/migrations/sqlite/0002_auth.sql
-- (db/parity.test.ts checks tables and columns match). Better Auth's conventions here: camelCase columns,
-- boolean, timestamptz.
-- Every table has row level security ENABLED and NO policies: the Data API (anon / authenticated) cannot
-- read or write them. The app connects as the table owner through the pooler.
-- Do not edit by hand. After a Better Auth upgrade add a NEW migration.

create table if not exists public."user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null, "twoFactorEnabled" boolean);
create table if not exists public."session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references public."user" ("id") on delete cascade, "activeOrganizationId" text);
create table if not exists public."account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references public."user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);
create table if not exists public."verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);
create table if not exists public."twoFactor" ("id" text not null primary key, "secret" text not null, "backupCodes" text not null, "userId" text not null references public."user" ("id") on delete cascade, "verified" boolean, "failedVerificationCount" integer, "lockedUntil" timestamptz);
create table if not exists public."organization" ("id" text not null primary key, "name" text not null, "slug" text not null unique, "logo" text, "createdAt" timestamptz not null, "metadata" text);
create table if not exists public."member" ("id" text not null primary key, "organizationId" text not null references public."organization" ("id") on delete cascade, "userId" text not null references public."user" ("id") on delete cascade, "role" text not null, "createdAt" timestamptz not null);
create table if not exists public."invitation" ("id" text not null primary key, "organizationId" text not null references public."organization" ("id") on delete cascade, "email" text not null, "role" text, "status" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "inviterId" text not null references public."user" ("id") on delete cascade);
create table if not exists public."rateLimit" ("id" text not null primary key, "key" text not null unique, "count" integer not null, "lastRequest" bigint not null);
create index if not exists "session_userId_idx" on public."session" ("userId");
create index if not exists "account_userId_idx" on public."account" ("userId");
create index if not exists "verification_identifier_idx" on public."verification" ("identifier");
create index if not exists "twoFactor_secret_idx" on public."twoFactor" ("secret");
create index if not exists "twoFactor_userId_idx" on public."twoFactor" ("userId");
create index if not exists "member_organizationId_idx" on public."member" ("organizationId");
create index if not exists "member_userId_idx" on public."member" ("userId");
create index if not exists "invitation_organizationId_idx" on public."invitation" ("organizationId");
create index if not exists "invitation_email_idx" on public."invitation" ("email");

-- Row level security on every table, with no policies.
alter table public."user" enable row level security;
alter table public."session" enable row level security;
alter table public."account" enable row level security;
alter table public."verification" enable row level security;
alter table public."twoFactor" enable row level security;
alter table public."organization" enable row level security;
alter table public."member" enable row level security;
alter table public."invitation" enable row level security;
alter table public."rateLimit" enable row level security;

-- Supabase roles: take away the default table grants too (defence in depth on top of RLS). The roles do not
-- exist on a plain Postgres (or PGlite in tests), hence the checks.
do $$
declare
  r text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if exists (select 1 from pg_roles where rolname = r) then
      execute format(
        'revoke all on table public."user", public."session", public."account", public."verification", public."twoFactor", public."organization", public."member", public."invitation", public."rateLimit" from %I',
        r
      );
    end if;
  end loop;
end;
$$;
